"""Add unique constraint and capacity column

Revision ID: b0f5be9d435a
Revises: 
Create Date: 2024-11-25 04:13:13.280411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0f5be9d435a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_user_workout_uc", "bookings", ["user_id", "workout_id"]
    )
    op.add_column("workouts", sa.Column("capacity", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "capacity")
    op.drop_constraint("_user_workout_uc", "bookings", type_="unique")
    # ### end Alembic commands ###
